//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_NEW.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMSEntities : DbContext
    {
        public IMSEntities()
            : base("name=IMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AssetMaster> tbl_AssetMaster { get; set; }
        public virtual DbSet<tbl_AssetType> tbl_AssetType { get; set; }
        public virtual DbSet<tbl_AssetUserMaping> tbl_AssetUserMaping { get; set; }
        public virtual DbSet<tbl_LocationMaster> tbl_LocationMaster { get; set; }
        public virtual DbSet<tbl_UserRegistration> tbl_UserRegistration { get; set; }
    }
}
