//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AssetMaster
    {
        public int AssetId { get; set; }
        public Nullable<int> AssetTypeId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string UserName { get; set; }
        public string SerialNo { get; set; }
        public string Ram { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public Nullable<System.DateTime> WarrantyStatus { get; set; }
        public string WindowKey { get; set; }
        public string Model { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual tbl_AssetType tbl_AssetType { get; set; }
        public virtual tbl_LocationMaster tbl_LocationMaster { get; set; }
    }
}
