//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AssetUserMaping
    {
        public int AssetUserMapplingid { get; set; }
        public Nullable<int> AssetId { get; set; }
        public string UserName { get; set; }
        public string Emailid { get; set; }
        public string UserLocationid { get; set; }
        public System.DateTime AssignDate { get; set; }
        public System.DateTime TransferDate { get; set; }
        public string AssetLocationId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string AssetsCode { get; set; }
    }
}
